[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install --no-save"]

[phases.build]
cmds = ["node generate-config.js", "bun build client.ts --outfile client.js --target browser"]

[start]
cmd = "bun run start"
